### ISSUE TITLE
Please configure atleast one user

### ISSUE THREAD

**Issue by BluGeni** [themoosman/mlapi#7]
When running docker-compose up I get this error:

```
mlapi    | EOFError: EOF when reading a line
mlapi    | [2020-07-07 20:10:12 +0000] [13] [INFO] Worker exiting (pid: 13)
mlapi    | [2020-07-07 20:10:12 +0000] [12] [ERROR] Exception in worker process
mlapi    | Traceback (most recent call last):
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
mlapi    |     worker.init_process()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process
mlapi    |     self.load_wsgi()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
mlapi    |     self.wsgi = self.app.wsgi()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
mlapi    |     self.callable = self.load()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
mlapi    |     return self.load_wsgiapp()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
mlapi    |     return util.import_app(self.app_uri)
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
mlapi    |     mod = importlib.import_module(module)
mlapi    |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
mlapi    |     return _bootstrap._gcd_import(name[level:], package, level)
mlapi    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mlapi    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mlapi    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
mlapi    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
mlapi    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
mlapi    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mlapi    |   File "/app/mlapi.py", line 195, in <module>
mlapi    |     db = Database.Database()
mlapi    |   File "/app/modules/db.py", line 24, in __init__
mlapi    |     name = input ('user name:')
mlapi    | EOFError: EOF when reading a line
mlapi    | [2020-07-07 20:10:12 +0000] [12] [INFO] Worker exiting (pid: 12)
mlapi    | Initializing log
mlapi    | DEBUG: secret filename: ./secrets.ini
mlapi    | DEBUG: Secret token found in config: !MLAPI_SECRET_KEY
mlapi    | INFO: --------| mlapi version: 1.0.7 |--------
mlapi    | DEBUG: Opening DB at ./db/db.json
mlapi    | DEBUG: DB engine ready
mlapi    | DEBUG: Initializing default users
mlapi    | --------------- User Creation ------------
mlapi    | Please configure atleast one user:
mlapi    | user name:[2020-07-07 20:10:12 +0000] [11] [ERROR] Exception in worker process
mlapi    | Traceback (most recent call last):
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
mlapi    |     worker.init_process()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process
mlapi    |     self.load_wsgi()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
mlapi    |     self.wsgi = self.app.wsgi()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
mlapi    |     self.callable = self.load()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
mlapi    |     return self.load_wsgiapp()
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
mlapi    |     return util.import_app(self.app_uri)
mlapi    |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
mlapi    |     mod = importlib.import_module(module)
mlapi    |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
mlapi    |     return _bootstrap._gcd_import(name[level:], package, level)
mlapi    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mlapi    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mlapi    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
...
```

**Comment by BluGeni** [comment]
I am not able to get into the container to create a user. Am I missing something to setup?
